WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))': /cgi-bin/webface2.cgi
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))': /cgi-bin/webface2.cgi
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))': /cgi-bin/webface2.cgi
Traceback (most recent call last):
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connectionpool.py", line 874, in urlopen
    return self.urlopen(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='services.healthtech.dtu.dk', port=443): Max retries exceeded with url: /cgi-bin/webface2.cgi (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cindy2270/miniconda3/envs/web/bin/pvacbind", line 8, in <module>
    sys.exit(main())
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/pvactools/tools/pvacbind/main.py", line 93, in main
    args[0].func.main(args[1])
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/pvactools/tools/pvacbind/run.py", line 108, in main
    pipeline.execute()
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/pvactools/lib/pipeline.py", line 756, in execute
    PostProcessor(**post_processing_params).execute()
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/pvactools/lib/post_processor.py", line 63, in execute
    self.call_net_chop()
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/pvactools/lib/post_processor.py", line 217, in call_net_chop
    NetChop(self.top_score_filter_fh.name, self.net_chop_fasta, self.net_chop_fh.name, self.net_chop_method, str(self.net_chop_threshold), self.file_type).execute()
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/pvactools/lib/net_chop.py", line 94, in execute
    response = self.query_netchop_server(http, staging_file, chosen_method, self.threshold)
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/pvactools/lib/net_chop.py", line 173, in query_netchop_server
    response = self.post_query(http, staging_file, chosen_method, threshold)
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/pvactools/lib/net_chop.py", line 189, in post_query
    response = http.post(
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/cindy2270/miniconda3/envs/web/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='services.healthtech.dtu.dk', port=443): Max retries exceeded with url: /cgi-bin/webface2.cgi (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
